// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetClipboardText():Promise<string>;

export function ParseAndCalculateTime(arg1:string):Promise<main.TimeResult>;
